[package]
name = "ci-gas-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
cosm-orc = { version = "0.5.0" }
anyhow = { version = "1.0.51"}
cw20-base = "0.12"
cw20 = "0.12"
serde_json = "1.0"
env_logger = "0.9.0"
