on: [pull_request]

name: Gas Benchmark

jobs:
  gas:
    name: Calculate gas costs in local juno
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci-gas-benchmark
    container:
      image: ghcr.io/cosmoscontracts/juno:v6.0.0
      env:
        PASSWORD: xxxxxxxxx
        STAKE_TOKEN: ujunox
        GAS_LIMIT: -1
        UNSAFE_CORS: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install deps
        run: apk --no-cache add rustup cargo

      - name: Setup Juno Node
        run: cd /opt && /opt/setup_and_run.sh juno10j9gpw9t4jsz47qgnkvl5n3zlm2fz72k67rxsg > /dev/null 2>&1 &

      - name: Calculate gas costs
        run: RUST_LOG=DEBUG cargo run

      - name: Debug
        run: cat ./gas_report.json

      - name: Move gas_report
        run: mv gas_report.json /new_gas_report.json

      - name: Checkout old sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Calculate gas costs
        run: RUST_LOG=DEBUG cargo run

      - name: Debug
        run: cat ./gas_report.json

      - name: Move gas_report
        run: mv gas_report.json /old_gas_report.json

      - name: Post gas diff to PR
        uses: de-husk/cosm-orc-gas-diff-action@v0.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          current_json: "/new_gas_report.json"
          old_json: "/old_gas_report.json"