on: [pull_request]

name: Gas Benchmark

jobs:
  gas:
    name: Calculate gas costs in local juno
    runs-on: ubuntu-latest
    env:
      ADMIN_ADDR: juno10j9gpw9t4jsz47qgnkvl5n3zlm2fz72k67rxsg
    defaults:
      run:
        working-directory: ./ci-gas-benchmark
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run Local Juno Node
        run: |
          docker run --rm -d --name juno \
            -e PASSWORD=xxxxxxxxx \
            -e STAKE_TOKEN=ujunox \
            -e GAS_LIMIT=100000000 \
            -e UNSAFE_CORS=true \
            -p 1317:1317 \
            -p 26656:26656 \
            -p 26657:26657 \
            -p 9090:9090 \
            ghcr.io/cosmoscontracts/juno:v9.0.0 /opt/setup_and_run.sh $ADMIN_ADDR

      - name: Calculate gas costs
        run: RUST_LOG=DEBUG cargo run

      - name: Debug
        run: cat ./gas_report.json

      - name: Post gas diff to PR
        uses: de-husk/cosm-orc-gas-diff-action@v0.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          current_json: "./ci-gas-benchmark/gas_report.json"
